export enum SortAlgorithm {
    BUBBLE_SORT = "BUBBLE_SORT",
    QUICK_SORT = "QUICK_SORT",
    SHELL_SORT = "SHELL_SORT",
    SELECTOR_SORT = "SELECTOR_SORT",
    INSERTION_SORT = "INSERTION_SORT",
    MERGE_SORT = "MERGE_SORT"
}